spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test_db
    username: test_user
    password: test_password

  jpa:
    hibernate:
      ddl-auto: none # R2DBC는 JPA를 사용하지 않음

logging:
  level:
    org.springframework.r2dbc.core: DEBUG